### ISSUE TITLE
WEB_PROCESS_CMD_PREFIX can not be used

### ISSUE THREAD

**Issue by elecro** [WebKitNix/webkitnix#16]
Nowadays the Nix port uses the LauncherGtk to start the webprocess and due to this the section "Debugging" in the Readme.nix can not be applied. The WEB_PROCESS_CMD_PREFIX is not used by the WebKit2 at all.

This was really a neat way of debugging the WebProcess. How should we restore this functionality? Should be implement it in the LauncherGtk or we'll create our own LauncherNix?

**Comment by qrwteyrutiyoup** [comment]
I took a quick look at implementing it in Gtk Launcher a few days ago, but at first glance it wasn't going to be that easy, since Gtk launches a libtool script (bash) which then launches the actual WebProcess binary. So, prefixing this libtool script with gdb, for instance, wasn't going to work (easily). 

To just restore this functionality for now - which I agree is neat - I think we could just clone the Gtk launcher and create our own Nix launcher.

**Comment by elecro** [comment]
Or can't we just go back to the Efl launcher?

**Comment by qrwteyrutiyoup** [comment]
Yeah, that's also an option, and we seem to keep switching between them. I am not sure why we changed back to Gtk launcher again, but it may have to do with the fact Efl workqueue is currently buggier: https://bugs.webkit.org/show_bug.cgi?id=114432 / https://bugs.webkit.org/show_bug.cgi?id=115332.

**Comment by elecro** [comment]
How about a solution like this elecro/webkitnix@888c54b6fd5765a2b7617df18259a1cab7c5e379 ?

**Comment by elecro** [comment]
Ahh... yeah a forgot to do a git add :) sorry. This is the patch's patch elecro/webkitnix@9ad14e1410c3f90ae7e9ac03fe65bae6e933cd60.

And a compare view: https://github.com/elecro/webkitnix/compare/webprocess_debug

**Comment by qrwteyrutiyoup** [comment]
Closing the issue, as commit e25ceb708 has landed. Thanks @elecro.
